apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nutbodyslam053/bd528:f6b526f39448074cc0d2636e02a4d2fb9db9e090
          ports:
            - containerPort: 5000
