apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nutbodyslam053/bd528:4d2f5676b76cecc19f2219ddccfc4ee3eaaad92d
          ports:
            - containerPort: 5000
